---
title: "S-I-R Model of COVID-19"
author: "Nick Loghmani"
runtime: shiny
output:
  html_notebook: default
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(flexdashboard)
library(tidyverse)
library(shiny)
library(deSolve)
library(ggrepel)
options( digits = 2, scipen = 99999)

library(dplyr)
library(readr)
url_us_confirmed <- paste("https://raw.githubusercontent.com/CSSEGISandData/", 
  "COVID-19/master/csse_covid_19_data/", "csse_covid_19_time_series/", 
  "time_series_covid19_confirmed_US.csv", sep = "")
url_global_confirmed <- paste("https://raw.githubusercontent.com/CSSEGISandData/", 
  "COVID-19/master/csse_covid_19_data/", "csse_covid_19_time_series/", 
  "time_series_covid19_confirmed_global.csv", sep = "")
url_us_death<-paste("https://raw.githubusercontent.com/CSSEGISandData/", 
  "COVID-19/master/csse_covid_19_data/", "csse_covid_19_time_series/", 
  "time_series_covid19_deaths_US.csv", sep = "")
url_global_death<-paste("https://raw.githubusercontent.com/CSSEGISandData/", 
  "COVID-19/master/csse_covid_19_data/", "csse_covid_19_time_series/", 
  "time_series_covid19_deaths_global.csv", sep = "")
url_recovered<-paste("https://raw.githubusercontent.com/CSSEGISandData/", 
  "COVID-19/master/csse_covid_19_data/", "csse_covid_19_time_series/", 
  "time_series_covid19_recovered_global.csv", sep = "")
data.us.confirmed<-read_csv(url_us_confirmed)
data.global.confirmed<-read_csv(url_global_confirmed)
data.global.recovered<-read_csv(url_recovered)
data.us.death<-read_csv(url_us_death)
data.global.death<-read_csv(url_global_death)
#data.confirmed
data.us.confirmed
data.global.confirmed
render_canada<-function(){
  
cad.data.confirmed<-rename(data.global.confirmed, province = "Province/State", country_region = "Country/Region") 
canada.data <- cad.data.confirmed %>%  pivot_longer(-c(province, country_region, Lat, Long), names_to = "Date", values_to = "cumulative_cases")%>% filter(country_region == "Canada")
canada.data

require(dplyr); 
require(RColorBrewer); 
require(ggplot2)
require(mapdata); 
require(maptools)
#install.packages("ggoplot")
canada <- map_data("worldHires", "Canada")
NAmap <- ggplot() + geom_polygon(data = canada, aes(x=long, y = lat, group = group),  fill = "white", color="black")  + coord_fixed(xlim = c(-135, -50),  ylim = c(40, 80), ratio = 1.2)
NAmap<-NAmap+geom_point(data=canada.data, aes(x=canada.data$Long, y=canada.data$Lat),fill="red", color = "black", shape=21, size=5.0)
NAmap
}

render_us<-function(){
library(maps)

us.data.confirmed<-rename(data.us.confirmed, province = "Province_State", country_region = "Country_Region") 
us.data <- us.data.confirmed %>%  pivot_longer(-c(province, country_region, Lat, Long), names_to = "Date", values_to = "cumulative_cases")%>% filter(country_region == "US")
us.data
usa <- map_data("usa")
NAmap <- ggplot() + geom_polygon(data = usa, aes(x=long, y = lat, group = group),  fill = "white", color="black")  + coord_fixed(xlim = c(-135, -50),  ylim = c(10, 50), ratio = 1.2)
NAmap<-NAmap+geom_point(data=us.data, aes(x=us.data$Long, y=us.data$Lat),fill="red", color = "black", shape=21, size=5.0)
NAmap
}

#-------------------------------
sirp_model <- function(time, state, parameters) {
  with(as.list(c(state, parameters)), {
    dS <- -beta * S * I
    dI <-  beta * S * I - gamma * I
    dR <-                 gamma * I
    dP <- 0
    return(list(c(dS, dI, dR, dP)))
  })
}
```




Context
==============================================

column{.tabset}
------------------------------------------------------

### The basic model

The Susceptible-Infected-Recovered (S-I-R) model helps to predict how an infectious agent could affect a susceptible population. We divide the population into three compartments;

1. Susceptible members of the population. A proportion of the population is susceptible to a disease. The disease vector transmits the pathogen through susceptibles. Some of the susceptibles become infected.

2. Infected members of the susceptible population. These susceptible members become infected, and can infect other susceptible members of the population. The rate at which susceptible members become infected is $\beta$, the transition rate from compartment S to I. This rate is defined as the basic reproductive number, $R0$, the average number of individuals each infected individual can infect in an otherwise unprotected population per the number of days the individual can transmit the pathogen.

3. Recovered members of the infected population. Some members of the infected population recover, the rest do not. We measure the transition rate from comparment I to S as $\gamma$, the inverse of the disease period. This is because in this model once the disease period is over, an individual instantaneously transfers to the R compartment.

4. A fourth compartment can be added that includes members who are immune or otherwise protected from infection.

$$
\begin{align}
\frac{dS}{dt} &= -\beta SI \\
\frac{dI}{dt} &= \beta S I – \gamma I \\
\frac{dR}{dt} &= \gamma I \\
\end{align}
$$
where,

$S=$ proportion of susceptible individuals in total population

$I=$ proportion of infected individuals in total population

$R=$ proportion of recovered individuals in total population

$\beta = cp =$ transmission parameter (rate of infection for susceptible-infected contact)

$c=$ number of contacts each host has per unit time (contact rate)

$p=$ probability of transmission of infection per contact (transmissibility)

$\gamma=$ recovery parameter (rate of infected transitioning to recovered)

### Assumptions

This model assumes:

- The population is closed and fixed, that is, no births or migration. 

- All individuals who transition from infected to recovered are permanently resistant to infection and there are no deaths. 

- The population is homogenous but only differ by their disease state. 

- Infection and that individual’s ability to infect susceptible individuals, occurs simultaneously.

### References

The SIR model originated woth the 1927 model of [Kermack and McKendrick](https://en.wikipedia.org/wiki/Kermack%E2%80%93McKendrick_theory).

A compendium of [compartmented models for epidemiology can ba found here.](http://homepages.warwick.ac.uk/~masfz/ModelingInfectiousDiseases/index.html)

This [online course Penn State](https://www.coursera.org/learn/epidemics) provides valuable background information and models to help us understnad the dynamics of an epidemic.

[Pellis et al.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3693038/) build probabilistic models of $R_0$.

The code in this simulation depends on and modifies the following sources:

- (https://sandsynligvis.dk/2019/03/06/building-a-shiny-app-to-show-the-impact-of-vaccines/)

- (https://cran.r-project.org/web/packages/epimdr/epimdr.pdf)

- (https://github.com/EconometricsBySimulation/SIR-shiny)

- (https://wgfoote.shinyapps.io/sir-p/#section-simulation)

Simulation
========================================

column {.sidebar}
----------------------------------------------------

```{r parameters, echo=FALSE}

sliderInput("pop_size",
                "Population size (millions):",
                min = 1, max = 1000, value = 6
    )
sliderInput("R_0",
                "Basic reproductive number (R0, # persons / infectious day):",
                min = .5, max = 20, value = 2.7
    )
sliderInput("prop_inf",
                "# infected at outbreak:",
                min = 1, max = 100, value = 2
    )
sliderInput("prop_prot",
                "Proportion protected (%):",
                min = 0, max = 100, value = 10
    )
sliderInput("eff_prot",
                "Effectiveness of Medication (Anti viral, Vaccination,..) (%):",
                min = 0, max = 100, value = 10
    )
sliderInput("inf_per",
                "Infection period (days):",
                min = 1, max = 30, value = 14
    )
sliderInput("time",
                "Time in days:",
                min = 1, max = 400, value = 200
    )

data_input <- reactive({
  init <- c(
        S = 1 - input$prop_inf / (input$pop_size*1000000) - input$prop_prot/100 * input$eff_prot/100,
        I = input$prop_inf /  (input$pop_size*1000000),
        R = 0,
        P = input$prop_prot / 100 * input$eff_prot / 100
      )
  ## beta: infection parameter; gamma: recovery parameter
  parameters <-c(
      beta = input$R_0 * 1 / input$inf_per,
      # * (1 - input$pvac/100*input$vaceff/100),
      gamma = 1 / input$inf_per)
  ## Time frame
  times <- seq(0, input$time, by = .2)
      ## Solve using ode (General Solver for Ordinary Differential Equations)
  out <- ode(
        y = init,
        times = times,
        func = sirp_model,
        parms = parameters
      )   
  #    out
  as.data.frame(out)
})

```

column
------------------------------------------

### Pervasiveness

```{r valueboxes}

renderValueBox({
  vb_1 <- data_input() %>% 
    filter(time == max(time)) %>% 
    select(R) %>% 
    mutate(R = round(100 * R, 2)) %>% paste0("%")
  valueBox(
      vb_1,
      "Proportion of full population that got the disease by end of time frame",
      icon = icon("fa_users"),
      color = "blue"
    )
  })
```

### Susceptibles exposure

```{r}
renderValueBox({
    valueBox(
      paste0(round(
        100 * (data_input() %>% filter(row_number() == n()) %>% mutate(res = (R + I) / (S + I + R)) %>% pull("res")), 2), "%"),
      "Proportion of susceptibles that will get the disease by end of the time frame",
      icon = icon("thermometer-full"),
      color = "green"
    )
  })
```


### Infectives reach

```{r}
renderValueBox({
    valueBox(
      paste0(round(input$R_0 *
                     (1 - input$prop_prot / 100 * input$eff_prot / 100), 2), ""),
      "Effective R0 for population at outbreak, when immunity is taken into account)",
      icon = icon("arrows-alt"),
      color = "red"
    )
  })
```

### Stopping the spread

```{r}
renderValueBox({
    valueBox(
      paste0(round(100 * (1 - 1 / (input$R_0)), 2), "%"),
      "Proportion of population that needs to be immune to prevent widespread infection",
      icon = icon("medkit"),
      color = "darkorange"
    )
  })
```

### H1N1 example

$R_0$ is the number of secondary cases produced by a single infected case over their infectious period $d$. We calculate $\beta=R_0/d$, the rate of transition from Susceptibles to Infectives, and $\gamma=1/d$, the rate of transition from Infectives to Susceptibles. Using H1N1 virus estimates of $R_0 = 2.23$ and infectious period of $d=7$ days $\beta = R_0/d = 2.23 / 7 =$ `r 2.23/7` and $\gamma=$ `r 1/7`. 

We can compare compare these calculations with the $R_0 = 15$ for measles. [Here are other values.](https://en.wikipedia.org/wiki/Basic_reproduction_number)

*Simulation settings*

For the settings on the left $R_0=$ `r reactive({input$R_0})`, $d=$ `r reactive({input$inf_per})`, so that $\beta=$ `r reactive({input$R_0/input$inf_per})` and $\gamma=$ `r reactive({1/input$inf_per})`.


column
----------------------------------------------------

### SIR-P Simulation

```{r plot}
renderPlot({
    out <-
      data_input() %>%
      gather(key, value, -time) %>%
      mutate(
        id = row_number(),
        key_0 = recode(
          key,
          S = "Susceptible (S)",
          I = "Infected (I)",
          R = "Recovered (R)",
          P = "Protected (P)"
        ),
        key_left = recode(
          key,
          S = "Susceptible (S)",
          I = "",
          R = "",
          P = "Protected (P)"
        ),
        key_right = recode(
          key,
          S = "",
          I = "Infected (I)",
          R = "Recovered (R)",
          P = ""
        )
      )

    ggplot(data = out,
           aes(
             x = time,
             y = value,
             group = key_0,
             col = key_0,
             label = key_0,
             data_id = id
           )) + # ylim(0, 1) +
      ylab("Proportion of full population") + xlab("Time (days)") +
      geom_line(size = 2) +
      geom_text_repel(
        data = subset(out, time == max(time)),
        aes(label = key_right),
        size = 6,
        segment.size  = 0.2,
        segment.color = "grey50",
        nudge_x = 0,
        hjust = 1,
        direction = "y"
      ) +
      geom_text_repel(
        data = subset(out, time == min(time)),
        aes(label = key_left),
        size = 6,
        segment.size  = 0.2,
        segment.color = "grey50",
        nudge_x = 0,
        hjust = 0,
        direction = "y"
      ) +
      theme(legend.position = "none") +
      scale_colour_manual(values = c("red", "green4", "black", "blue")) +
      scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
      theme(
        rect=element_rect(size=0),
        legend.position="none",
        panel.background=element_rect(fill="transparent", color=NA),
        plot.background=element_rect(fill="transparent", color=NA),
        legend.key = element_rect(fill = "transparent", color = "transparent")
      )
     #render_canada()
    
})
```

```{r plot2}
renderPlot({
     render_canada()
})
```

```{r plot3}
renderPlot({
     render_us()
})
```